chore(deps): update dependency tailwindcss to v4 (#349)
* chore(deps): update dependency tailwindcss to v4

| datasource | package     | from   | to     |
| ---------- | ----------- | ------ | ------ |
| npm        | tailwindcss | 3.4.17 | 4.1.17 |

* config: properly set up tailwind v4

* ci: force status checks

* config,refactor: move imports into deno.json file

* config: adjust formatting and linting exclusions

* config: fix deno tasks

* ci: fix workflow trigger events

* ide: make settings adjustments

* deps: update deno lock

* cleanup: remove unused file

[skip ci]

* docs: update api docs for Velaptor version v1.0.0-preview.44

* WIP - Loading content guide

* WIP - Loading content guide

* config: improve issue templates

* other: remove old dev tools

* config: add create pr script to deno tasks

* chore: create a dev script to create local velaptor nuget package

* ide: set formatting settings for typescript files

* ide: add words to dictionary

* config: add deno task to create local velaptor nuget pkg

* chore: update space shooter game to latest velaptor version

* config: remove upcoming deprecated docusaurus setting

* chore: update guide projects to use Velaptor v1.0.0-preview.44

* chore: update guide project links

* deps: update pnpm lock file

* chore: simplify os detection

* chore: remove v1.0.0-preview-38 API docs

* chore: add v1.0.0-preview.44 API docs

* ci: update actions

* ci: update workflows formatting to meet coding standards

* ci: remove sync related workflows

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: CalvinWilkinson <kinsondigital@gmail.com>

diff --git a/.github/workflows/feature-branch-status-check.yml b/.github/workflows/feature-branch-status-check.yml
--- a/.github/workflows/feature-branch-status-check.yml
+++ b/.github/workflows/feature-branch-status-check.yml
@@ -1,55 +1,51 @@
 name: ✅Feature Branch Status Check
 
-
 defaults:
   run:
     shell: pwsh
 
-
 on:
   pull_request_target:
-    branches: main
-
+    branches: [main]
 
 jobs:
   feature_branch_status_check:
     name: Feature Branch Status Check
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v5
+      - uses: actions/checkout@v5
 
-    - name: Validate Branch
-      run: |
-        $renovateRegEx = "^renovate/.+$";
-        $regex = '${{ vars.FEATURE_BRANCH_REGEX }}';
+      - name: Validate Branch
+        run: |
+          $renovateRegEx = "^renovate/.+$";
+          $regex = '${{ vars.FEATURE_BRANCH_REGEX }}';
 
-        $headBranch = "${{ github.head_ref }}";
-        $baseBranch = "main";
+          $headBranch = "${{ github.head_ref }}";
+          $baseBranch = "main";
 
-        $headBranchInvalid = $false;
-        $baseBranchInvalid = $false;
+          $headBranchInvalid = $false;
+          $baseBranchInvalid = $false;
 
-        # If the PR branch is a Renovate branch, it is valid and do not check for a feature branch.
-        if ($headBranch -match $renovateRegEx) {
-            Write-Host "::notice::The head branch '$headBranch' is a Renovate branch.";
-            exit 0;
-        }
+          # If the PR branch is a Renovate branch, it is valid and do not check for a feature branch.
+          if ($headBranch -match $renovateRegEx) {
+              Write-Host "::notice::The head branch '$headBranch' is a Renovate branch.";
+              exit 0;
+          }
 
-        if ($headBranch -match $regex) {
-            Write-Host "::notice::The head branch '$headBranch' is valid.";
-        } else {
-            Write-Host "::error::The head branch '$headBranch' is invalid.";
-            $headBranchInvalid = $true;
-        }
+          if ($headBranch -match $regex) {
+              Write-Host "::notice::The head branch '$headBranch' is valid.";
+          } else {
+              Write-Host "::error::The head branch '$headBranch' is invalid.";
+              $headBranchInvalid = $true;
+          }
 
-        if ($baseBranch -eq "main") {
-            Write-Host "::notice::The base branch '$baseBranch' is valid.";
-        } else {
-            Write-Host "::error::The base branch '$baseBranch' is invalid.";
-            $baseBranchInvalid = $true;
-        }
+          if ($baseBranch -eq "main") {
+              Write-Host "::notice::The base branch '$baseBranch' is valid.";
+          } else {
+              Write-Host "::error::The base branch '$baseBranch' is invalid.";
+              $baseBranchInvalid = $true;
+          }
 
-        if ($headBranchInvalid -or $baseBranchInvalid) {
-            exit 1;
-        }
-
+          if ($headBranchInvalid -or $baseBranchInvalid) {
+              exit 1;
+          }
