ci: rename release to production release and remove workflow

diff --git a/.github/workflows/prod-release.yml b/.github/workflows/prod-release.yml
--- a/.github/workflows/prod-release.yml
+++ b/.github/workflows/prod-release.yml
@@ -1,4 +1,4 @@
-name: 🚀API Docs Release
+name: 🚀Production Release
 
 
 defaults:
@@ -30,34 +30,34 @@ jobs:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     steps:
-    # - name: "Validate Branch"
-    #   run: |
-    #     $branch = "${{ github.ref }}";
+    - name: "Validate Branch"
+      run: |
+        $branch = "${{ github.ref }}";
         
-    #     if ($branch -ne "refs/heads/master") {
-    #       Write-Host "::error::This workflow can only be run on the master branch.";
-    #       exit 1; # Fail workflow
-    #     }
+        if ($branch -ne "refs/heads/master") {
+          Write-Host "::error::This workflow can only be run on the master branch.";
+          exit 1; # Fail workflow
+        }
 
     - uses: actions/checkout@v3
 
-    # - name: "Setup NodeJS"
-    #   uses: actions/setup-node@v3
-    #   with:
-    #     node-version: 18.14.2
+    - name: "Setup NodeJS"
+      uses: actions/setup-node@v3
+      with:
+        node-version: 18.14.2
 
-    # - name: "Setup YARN"
-    #   run: npm install --global yarn
+    - name: "Setup YARN"
+      run: npm install --global yarn
 
-    # - name: "Setup Docusaurus"
-    #   run: yarn install
+    - name: "Setup Docusaurus"
+      run: yarn install
 
     - name: "Setup Deno"
       uses: denoland/setup-deno@v1
       with:
         deno-version: v1.32.x
 
-    - name: "Apply Version To Document Site"
+    - name: "Update Website Version"
       id: apply_version_to_site
       run: |
         $outputFilePath = $GITHUB_OUTPUT;
@@ -76,20 +76,20 @@ jobs:
           "${{ github.workspace }}/.github/cicd/workflow-helpers/WebsiteVersionUpdater.ts" `
           "$outputFilePath";
 
-    # - name: "Build Site"
-    #   run: yarn build
+    - name: "Build Site"
+      run: yarn build
 
-    # - name: "Setup Pages"
-    #   uses: actions/configure-pages@v3 # https://github.com/marketplace/actions/configure-github-pages
+    - name: "Setup Pages"
+      uses: actions/configure-pages@v3 # https://github.com/marketplace/actions/configure-github-pages
 
-    # - name: "Upload Artifact"
-    #   uses: actions/upload-pages-artifact@v1.0.8
-    #   with:
-    #     path: '${{ github.workspace }}/build'
+    - name: "Upload Artifact"
+      uses: actions/upload-pages-artifact@v1.0.8
+      with:
+        path: '${{ github.workspace }}/build'
 
-    # - name: "Deploy to GitHub Pages"
-    #   id: deployment
-    #   uses: actions/deploy-pages@v2
+    - name: "Deploy to GitHub Pages"
+      id: deployment
+      uses: actions/deploy-pages@v2
 
     - name: "Create Release Tag"
       run: |
